// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using flourishbackend.Data;

#nullable disable

namespace flourishbackend.Migrations
{
    [DbContext(typeof(FlourishDbContext))]
    [Migration("20260325150455_AddJournalEntryCreatedDate")]
    partial class AddJournalEntryCreatedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Flourish.Models.Affirmation", b =>
                {
                    b.Property<Guid>("AffirmationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AffirmationId");

                    b.ToTable("Affirmations");
                });

            modelBuilder.Entity("Flourish.Models.AffirmationReaction", b =>
                {
                    b.Property<Guid>("AffirmationReactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AffirmationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("AffirmationReactionId");

                    b.HasIndex("AffirmationId");

                    b.HasIndex("UserId");

                    b.ToTable("AffirmationReactions");
                });

            modelBuilder.Entity("Flourish.Models.BabyActivity", b =>
                {
                    b.Property<Guid>("BabyActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float?>("AmountOz")
                        .HasColumnType("REAL");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BreastSide")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("BabyActivityId");

                    b.HasIndex("BabyId");

                    b.HasIndex("UserId");

                    b.ToTable("BabyActivities");
                });

            modelBuilder.Entity("Flourish.Models.BabyMood", b =>
                {
                    b.Property<Guid>("BabyMoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BabyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MoodValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("BabyMoodId");

                    b.HasIndex("BabyId");

                    b.HasIndex("UserId");

                    b.ToTable("BabyMoods");
                });

            modelBuilder.Entity("Flourish.Models.BabyProfile", b =>
                {
                    b.Property<Guid>("BabyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BabyDateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("BabyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("BabyId");

                    b.HasIndex("UserId");

                    b.ToTable("BabyProfiles");
                });

            modelBuilder.Entity("Flourish.Models.JournalEntry", b =>
                {
                    b.Property<Guid>("JournalEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShareWithPartner")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("JournalEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("Flourish.Models.MoodEntry", b =>
                {
                    b.Property<Guid>("MoodEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoodLabel")
                        .HasColumnType("TEXT");

                    b.Property<int>("MoodValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("MoodEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("MoodEntries");
                });

            modelBuilder.Entity("Flourish.Models.SavedResource", b =>
                {
                    b.Property<Guid>("SavedResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("SavedResourceId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedResources");
                });

            modelBuilder.Entity("Flourish.Models.SupportProfile", b =>
                {
                    b.Property<Guid>("SupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShareBabyTracking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShareJournals")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShareMood")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportType")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("SupportId");

                    b.HasIndex("UserId");

                    b.ToTable("SupportProfiles");
                });

            modelBuilder.Entity("Flourish.Models.SupportRequest", b =>
                {
                    b.Property<Guid>("SupportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("SupportRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("SupportRequests");
                });

            modelBuilder.Entity("Flourish.Models.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeFeatures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationsFeedingEnabled")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("NotificationsFeedingTimes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationsMoodEnabled")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("NotificationsMoodTimes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotificationsNapEnabled")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("NotificationsNapTimes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Flourish.Models.AffirmationReaction", b =>
                {
                    b.HasOne("Flourish.Models.Affirmation", "Affirmation")
                        .WithMany()
                        .HasForeignKey("AffirmationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flourish.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Affirmation");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Flourish.Models.BabyActivity", b =>
                {
                    b.HasOne("Flourish.Models.BabyProfile", "BabyProfile")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flourish.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BabyProfile");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Flourish.Models.BabyMood", b =>
                {
                    b.HasOne("Flourish.Models.BabyProfile", "BabyProfile")
                        .WithMany()
                        .HasForeignKey("BabyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flourish.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BabyProfile");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Flourish.Models.BabyProfile", b =>
                {
                    b.HasOne("Flourish.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Flourish.Models.JournalEntry", b =>
                {
                    b.HasOne("Flourish.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Flourish.Models.MoodEntry", b =>
                {
                    b.HasOne("Flourish.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Flourish.Models.SavedResource", b =>
                {
                    b.HasOne("Flourish.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Flourish.Models.SupportProfile", b =>
                {
                    b.HasOne("Flourish.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Flourish.Models.SupportRequest", b =>
                {
                    b.HasOne("Flourish.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
